server:
  port: 8080

email:
  mailgun:
    apiKey: YOUR_MAILGUN_API_KEY
    domain: YOUR_MAILGUN_DOMAIN
    url: https://api.mailgun.net/v3
  sendgrid:
    apiKey: YOUR_SENDGRID_API_KEY
    url: https://api.sendgrid.com/v3
